In [1]:
import pandas as pd

In [6]:
year_2015_2016 = pd.read_csv('Season_2015-16.csv')
year_2016_2017 = pd.read_csv('Season_2016-17.csv')
year_2017_2018 = pd.read_csv('Season_2017-18.csv')
year_2018_2019 = pd.read_csv('Season_2018-19.csv')
year_2019_2020 = pd.read_csv('Season_2019-20.csv')

In [7]:
#Add all 5 seasons
df = pd.concat(map(pd.read_csv,['Season_2015-16.csv', 'Season_2016-17.csv',
                                'Season_2017-18.csv','Season_2018-19.csv', 
                               'Season_2019-20.csv']), ignore_index=True)
print(df)

      Unnamed: 0            Date       Team 1   FT   HT       Team 2  \
0              0  Sat Aug 8 2015  Bournemouth  0-1  0-0  Aston Villa
1              1  Sat Aug 8 2015      Chelsea  2-2  2-1      Swansea
2              2  Sat Aug 8 2015      Everton  2-2  0-1      Watford
3              3  Sat Aug 8 2015    Leicester  4-2  3-0   Sunderland
4              4  Sat Aug 8 2015   Man United  1-0  1-0    Tottenham
...          ...             ...          ...  ...  ...          ...
1803         283  Sat Mar 7 2020       Wolves  0-0  0-0     Brighton
1804         284  Sat Mar 7 2020      Burnley  1-1  1-0    Tottenham
1805         285  Sun Mar 8 2020      Chelsea  4-0  2-0      Everton
1806         286  Sun Mar 8 2020   Man United  2-0  1-0     Man City
1807         287  Mon Mar 9 2020    Leicester  4-0  1-0  Aston Villa

         Season
0     2015-2016
1     2015-2016
2     2015-2016
3     2015-2016
4     2015-2016
...         ...
1803  2019-2020
1804  2019-2020
1805  2019-2020
1806  2019-2020
1807  2019-2020

[1808 rows x 7 columns]

In [8]:
df = df.rename(columns={'Team 1': 'home_team', 'FT': 'full_Time_score', 
                        'HT': 'half_Time_score', 'Team 2': 'away_team'})
df

,Date,home_team,full_Time_score,half_Time_score,away_team,Season
0,Sat Aug 8 2015,Bournemouth,0-1,0-0,Aston Villa,2015-2016
1,Sat Aug 8 2015,Chelsea,2-2,2-1,Swansea,2015-2016
2,Sat Aug 8 2015,Everton,2-2,0-1,Watford,2015-2016
3,Sat Aug 8 2015,Leicester,4-2,3-0,Sunderland,2015-2016
4,Sat Aug 8 2015,Man United,1-0,1-0,Tottenham,2015-2016
...,...,...,...,...,...,...
1803,Sat Mar 7 2020,Wolves,0-0,0-0,Brighton,2019-2020
1804,Sat Mar 7 2020,Burnley,1-1,1-0,Tottenham,2019-2020
1805,Sun Mar 8 2020,Chelsea,4-0,2-0,Everton,2019-2020
1806,Sun Mar 8 2020,Man United,2-0,1-0,Man City,2019-2020
1807,Mon Mar 9 2020,Leicester,4-0,1-0,Aston Villa,2019-2020

In [7]:
df.isnull().sum()

Date               0
home_team          0
full_Time_score    0
half_Time_score    0
away_team          0
Season             0
dtype: int64

In [8]:
df.to_csv('Merged-Seasons.csv')